### ISSUE TITLE
Issues at installing nvdla/vp

### ISSUE THREAD

**Issue by nicolast0604** [nvdla/vp#44]
/home/nicolast0604/vp/hw/outdir/nv_full/cmod/release/lib/libnvdla_cmod.so: undefined reference to `sc_core::sc_vector_base::make_name(char const*, unsigned long)'
collect2: error: ld returned 1 exit status
CMakeFiles/aarch64_toplevel.dir/build.make:106: recipe for target 'aarch64_toplevel' failed
make[2]: *** [aarch64_toplevel] Error 1
CMakeFiles/Makefile2:111: recipe for target 'CMakeFiles/aarch64_toplevel.dir/all' failed
make[1]: *** [CMakeFiles/aarch64_toplevel.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wang18112020007** [comment]
I have the same error.

**Comment by fisherxue** [comment]
Are you installing on ubuntu 14.04 / gcc 4.8.4?

**Comment by wang18112020007** [comment]
I fixed the error when I re_installed systemc_2.3.0.

**Comment by hariharan765** [comment]
I tried reinstalling systemc2.3.0. I still face this issue. 

I ran the following commands:

cd <path_nvdla>/vp
export CC=<path_gcc482>/bin/gcc
export CXX=<path_gcc482>/bin/g++
cmake -DCMAKE_INSTALL_PREFIX=build -DSYSTEMC_PREFIX=/usr/local/systemc230/ -DNVDLA_HW_PREFIX=<path_nvdla>/hw/ -DNVDLA_HW_PROJECT=nv_full
make

And I see the following logs:

[ 86%] Linking CXX executable aarch64_toplevel
**/home/hariharans/localwork/nvdla/hw/outdir/nv_full/cmod/release/lib/libnvdla_cmod.so: undefined reference to `sc_core::sc_vector_base::make_name(char const*, unsigned long)'**
collect2: error: ld returned 1 exit status
CMakeFiles/aarch64_toplevel.dir/build.make:106: recipe for target 'aarch64_toplevel' failed
make[2]: *** [aarch64_toplevel] Error 1
make[2]: Leaving directory '/home/hariharans/localwork/nvdla/vp'
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/aarch64_toplevel.dir/all' failed
make[1]: *** [CMakeFiles/aarch64_toplevel.dir/all] Error 2
make[1]: Leaving directory '/home/hariharans/localwork/nvdla/vp'
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2


Attached verbose logs (VERBOSE=1) as well. I can see that libsystemc.so is being included in linker path.


[vp_make_fail_logs_verbose.txt](https://github.com/nvdla/vp/files/3862299/vp_make_fail_logs_verbose.txt)
hariharans@hariharans:~$ strings /usr/local/systemc230/lib-linux64/libsystemc.so | grep make_name
_ZN7sc_core14sc_vector_base9make_nameB5cxx11EPKcm
_ZN7sc_core14sc_vector_base9make_nameB5cxx11EPKcm

**Comment by Owen199x** [comment]
please use the g++ 4.8.5 and gcc 4.85,
please recompile the systemc again,
please recompile the hw again,
then you can get the result for pass.

**Comment by kevinli-hw** [comment]
Sorry to comment after such a long time, I have the same error and can't solve it by reinstalling. I'm using ubuntu18.04 with gcc/g++-4.8.5. I'm wondering if you fixed this error eventually. If so, how did you do that? Should I reinstall everything on ubuntu16.04 or 14.04 instead of 18.04?

**Comment by kevinli-hw** [comment]
Fix it after reinstalling system-C finally... It appears that the gcc compiler I used to compile system-C and vp are different, which caused the error.
